language: cpp
sudo: required
dist: trusty
compiler:
- gcc
os:
- linux

before_script:
- git clone https://github.com/oxygine/oxygine-framework $OXYGINE_PATH
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-7 build-essential zlib1g-dev libsdl2-2.0-0 libglu1-mesa libglu1-mesa-dev libsdl2-dev libpng-dev libpng12-dev graphviz doxygen
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 60

script:
- cmake -DCMAKE_BUILD_TYPE=Release .
- cmake --build .

env:
  global:
  - OXYGINE_PATH=/home/travis/build/oxygine-framework

